Citizen.CreateThread(function()
    AddTextEntry("amels200", "AMELS200")
    AddTextEntry("650e", "Sea Ray 650E")
    AddTextEntry("autoflagger", "DOT Flagger Trailer")
    AddTextEntry("dotf150", "DOT 2021 Ford F-150")
    AddTextEntry("dotram", "DOT 2015 Dodge Ram")
    AddTextEntry("rollback1", "DOT Ford F-250 Tow Truck")
    AddTextEntry("rollback14", "DOT Ford F-250 Tow Truck (4 Door)")
    AddTextEntry("rollback4", "DOT Mack Tow Truck")
    AddTextEntry("segwayciv", "Segway")
    AddTextEntry("iak_wheelchair", "Wheelchair")
    AddTextEntry("galaxyroamer", "Galaxy Roamer Bus RV")
    AddTextEntry("workf150", "Work 2018 Ford F-150")
    AddTextEntry("21z900", "Kawasaki Z900")
    AddTextEntry("g_xlcr", "Harley Davidson Sportser")
    AddTextEntry("r1200gsec", "BMW R1200")
    AddTextEntry("pcx160_2025", "PCX 160")
    AddTextEntry("ip_m1000rr_23", "BMW M1000RR")
    AddTextEntry("s1000sec", "BMW S1000R")
    AddTextEntry("goldwing", "Honda Goldwing")
    AddTextEntry("sahara300", "Sahara 300")
    AddTextEntry("117", "Harley Davidson Bike")
    AddTextEntry("22chevango", "2012 Chevy Express (Cargo)")
    AddTextEntry("22chevan", "2012 Chevy Express (Passenger)")
    AddTextEntry("jogger", "Benefactor Jogger")
    AddTextEntry("joggerpas", "Benefactor Jogger (Passenger)")
    AddTextEntry("imperialev", "Benefactor Imperial EV")
    AddTextEntry("imperialpas", "Benefactor Imperial (Passenger)")
    AddTextEntry("imperial", "Benefactor Imperial")
    AddTextEntry("nspeedo", "Vapid Speedo Express")
    AddTextEntry("peacemaker", "Gallavanter Peacemaker")
    AddTextEntry("peacemaker4", "Gallavanter Peacemaker (Bed)")
    AddTextEntry("peacemaker6", "Gallavanter Peacemaker (Net)")
    AddTextEntry("f150", "2015 Ford F-150 SVT")
    AddTextEntry("f150army", "2015 Ford F-150 (Army)")
    AddTextEntry("rubicon24", "2024 Jeep Rubicon")
    AddTextEntry("nsandstorm3", "Vapid Sandstorm (Single Cab)")
    AddTextEntry("nsandstorm2", "Vapid Sandstorm (Dually)")
    AddTextEntry("nsandstorm", "Vapid Sandstorm (Crew Cab)")
    AddTextEntry("hellenstorm", "Vapid Hellenstorm")
    AddTextEntry("CyberTruckV", "Tesla Cybertruck")
    AddTextEntry("wildtrak", "Ford Bronco Wildtrack")
    AddTextEntry("velociraptor", "Ford F-150 Velociraptor")
    AddTextEntry("f35019", "2019 Ford F-350")
    AddTextEntry("22mavxl", "2022 Ford Maverick")
    AddTextEntry("22f450xl", "2022 Ford F450 XL Superduty")
    AddTextEntry("21f250", "2021 Ford F-250 Superduty")
    AddTextEntry("21f150", "2021 Ford F-150")
    AddTextEntry("21brooff", "2021 Ford Bronco Sport")
    AddTextEntry("21bro", "2021 Ford Bronco")
    AddTextEntry("18raptor", "2018 Ford F-150 Raptor")
    AddTextEntry("22silvwt", "2021 Chevy Silverado")
    AddTextEntry("22silvltz", "2021 Chevy Silverado LTZ")
    AddTextEntry("cararv", "Vapid Caracara 4x4 RV")
    AddTextEntry("sandkingRV", "Vapid Sandking RV")
    AddTextEntry("guardianrv", "Vapid Guardian RV")
    AddTextEntry("sandroamer", "Vapid Sandroamer RV")
    AddTextEntry("f15078", "1978 Ford F-150")
    AddTextEntry("teslax", "Tesla Model X")
    AddTextEntry("mache", "Ford MachE")
    AddTextEntry("4runner", "Toyota 4 Runner")
    AddTextEntry("g63sec20", "Mercedes AMG G63")
    AddTextEntry("urus", "Lamborghini Urus")
    AddTextEntry("bbentayga", "Bentley Bentayga")
    AddTextEntry("vxr", "Toyota VXR V8")
    AddTextEntry("16i3", "2016 BMW I3")
    AddTextEntry("tundra2021", "2021 Toyota Tundra")
    AddTextEntry("expmax20", "2020 Ford Expedition Platinum")
    AddTextEntry("22exp", "2022 Ford Expedition")
    AddTextEntry("21dura", "2021 Dodge Durango Citreol")
    AddTextEntry("19exp", "2019 Ford Explorer")
    AddTextEntry("15expxl", "2015 Ford Expedition")
    AddTextEntry("15exp", "2015 Ford Expedition Platinum")
    AddTextEntry("02tahoe", "2002 Chevy Tahoe")
    AddTextEntry("ncavalcade", "Albany Cavalcade")
    AddTextEntry("20tahoeciv", "2018 Chevy Tahoe (Retired)")
    AddTextEntry("16fpiuciv", "2016 Ford FPIU (Retired)")
    AddTextEntry("sec rav424", "2021 Toyota Rav4 Hybrid")
    AddTextEntry("tahoe08", "2008 Chevy Tahoe")
    AddTextEntry("21subur", "2021 Chevy Suburban")
    AddTextEntry("SubaruWagonWRX", "Subaru Impreza WRX")
    AddTextEntry("15carv", "2015 Dodge Grand Caravan")
    AddTextEntry("mig", "Ferrari")
    AddTextEntry("jeskoattack24", "Koenigsegg Jesko")
    AddTextEntry("f812", "Ferrari F812")
    AddTextEntry("italigtb2", "Ferrari Itali GTB")
    AddTextEntry("f4090", "Ferrari F4090")
    AddTextEntry("czr1", "Chevy Corvette ZR")
    AddTextEntry("c7", "Chevy Corvette C7")
    AddTextEntry("evija", "2020 Lotus Evija")
    AddTextEntry("20gt500", "2020 Ford Mustang GT")
    AddTextEntry("bolide", "2020 Bugatti Bolide")
    AddTextEntry("22m5", "2022 BMW M5 CS")
    AddTextEntry("22bengt", "2022 Bentley GT Continental")
    AddTextEntry("mustang68", "1968 Ford Mustang")
    AddTextEntry("nbbatur", "Bentley Batur")
    AddTextEntry("ypg205t16a", "Peugeot 205 (Rally)")
    AddTextEntry("ypg205t16b", "Peugeot 205")
    AddTextEntry("majfd", "Mazda RX-7")
    AddTextEntry("99viper", "1999 Dodge Viper")
    AddTextEntry("cam8tun", "Toyota Camry XSE")
    AddTextEntry("z32", "Fairlady Z 300ZX")
    AddTextEntry("ap2", "Honda S2000")
    AddTextEntry("focusrs", "2017 Ford Focus RS")
    AddTextEntry("s63w222", "Mercedes AMG S63")
    AddTextEntry("rufrgt8", "Porshe GT8")
    AddTextEntry("24mustdh", "2024 Ford Mustang GT")
    AddTextEntry("cali57", "Ferrari 250 GT")
    AddTextEntry("59coronet", "1959 Dodge Coronet")
    AddTextEntry("chrysler11", "Chrysler")
    AddTextEntry("21ltz", "2021 Chevy Camero ZL1")
    AddTextEntry("gtr50", "Nissan GT-R50")
    AddTextEntry("r820", "Audi R8")
    AddTextEntry("golf8gti", "VW Golf 8 GTI")
    AddTextEntry("golfgti7", "VW Golf 7 GTI")
    AddTextEntry("tltypes", "Honda Acura TLS")
    AddTextEntry("teslapd", "Tesla Model S")
    AddTextEntry("tmodel", "Tesla Model 3")
    AddTextEntry("c6320", "Mercedes AMG C63S")
    AddTextEntry("77monaco", "1977 Dodge Monaco")
    AddTextEntry("22char", "2022 Dodge Charger")
    AddTextEntry("08char", "2008 Dodge Charger")
    AddTextEntry("impa6", "2006 Chevy Impala LS")
    AddTextEntry("22530i", "2022 BMW 530I Wagon")
    AddTextEntry("22ct4", "2022 Cadillac Ct4")
    AddTextEntry("13malibu", "2023 Chevy Malibu")
    AddTextEntry("03impa", "2003 Chevy Impala")
    AddTextEntry("cmr11", "2011 Toyota Camry")
    AddTextEntry("vic11", "2011 Ford Crown Victoria")
    AddTextEntry("11cvpiciv", "2011 Ford CVPI (Retired)")
    AddTextEntry("18chargerci", "2018 Dodge Charger PPV (Retired)")
    AddTextEntry("m3e36", "BMW M3 E36")
    AddTextEntry("22rs5", "2022 Audi rs5")
    AddTextEntry("22m5sal", "2022 BMW M5")
    AddTextEntry("m422", "2022 BMW M4")
    AddTextEntry("21avant", "2021 Audi RS5 Avant")
    AddTextEntry("nbmazda3", "2020 Mazda 3")
    AddTextEntry("saab93aeroc", "Saab 93")
    AddTextEntry("rbmwm3f80", "BMW M3 F80")
    AddTextEntry("piccolo", "Grotti Piccolo")
    AddTextEntry("twingo", "Renault Twingo")
    AddTextEntry("segway", "LSPD Segway")
    AddTextEntry("rav4hyb", "LSPD Detective 2024 Toyota Rav4")
    AddTextEntry("25umfpiu", "LSPD Detective 2025 Ford Explorer")
    AddTextEntry("umdet1", "LSPD Detective 2022 Dodge Durango")
    AddTextEntry("pdfpiu", "LSPD 2023 Ford FPIU")
    AddTextEntry("pdbike", "LSPD 2016 BMW R1200RT")
    AddTextEntry("pdcvpi", "LSPD 2011 Ford CVPI")
    AddTextEntry("pdtaurus", "LSPD 2018 Ford Taurus")
    AddTextEntry("pdcharger", "LSPD 2021 Dodge Charger")
    AddTextEntry("pdimpala", "LSPD 2011 Chevy Impala")
    AddTextEntry("pdcaprice", "LSPD 2013 Chevy Caprice")
    AddTextEntry("pdtahoe", "LSPD 2021 Chevy Tahoe")
    AddTextEntry("pdtruck", "LSPD 2023 Chevy Silverado")

end)
